baseURL = 'https://www.zrosario.com/'
languageCode = 'en-us'
title = 'zach rosario blog'
theme = "ritzy"
[params]
  author = "Zachary Rosario"
  description = "CS and STS student at Stevens Institute of Technology. Here you will find my writings."